# Site settings
title: Sauhard Shrestha
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Learning to create. Creating to learn.
   

baseurl: "" # the subpath of your site, e.g. /blog
url: "http://yourdomain.com" # the base hostname & protocol for your site

email_address: sauahrd192@gmail.com
instagram_username: sauhard.stha
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
permalink: pretty

include:
  - art.html
  - art_preview.html